services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: ethnoatlas
      POSTGRES_USER: ethnoatlas
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: